// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn9vPCMIFOzR7p_tMMxYZw3-9MRUomrYE',
    appId: '1:966840317747:web:e0576d6669c855986a3046',
    messagingSenderId: '966840317747',
    projectId: 'twodu-nnisarg',
    authDomain: 'twodu-nnisarg.firebaseapp.com',
    storageBucket: 'twodu-nnisarg.appspot.com',
    measurementId: 'G-2L5MCVMKFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyConD8J3v-7d1anU2dBmtZvjLIcqXplYo4',
    appId: '1:966840317747:android:072de6749e20f8826a3046',
    messagingSenderId: '966840317747',
    projectId: 'twodu-nnisarg',
    storageBucket: 'twodu-nnisarg.appspot.com',
  );
}
